-- EcoDrive legacy read compatibility views — Sprint 12D design only.
-- The views deliberately use legacy table names in a new canonical DB.
-- Writes are retargeted to canonical tables by persistence adapters in Sprint 12E.

CREATE VIEW "vde_db" AS
SELECT
    "id" AS "id",
    "created_at" AS "created_at",
    "updated_at" AS "updated_at",
    "legislation" AS "legislation",
    "category" AS "category",
    "make" AS "make",
    "model" AS "model",
    "year" AS "year",
    "notes" AS "notes",
    "engine_type" AS "engine_type",
    "engine_model" AS "engine_model",
    "engine_size_l" AS "engine_size_l",
    "engine_aspiration" AS "engine_aspiration",
    "transmission_type" AS "transmission_type",
    "transmission_model" AS "transmission_model",
    "mass_kg" AS "mass_kg",
    "inertia_class" AS "inertia_class",
    "cda_m2" AS "cda_m2",
    "weight_dist_fr_pct" AS "weight_dist_fr_pct",
    "payload_kg" AS "payload_kg",
    "tire_size" AS "tire_size",
    "tire_rr_note" AS "tire_rr_note",
    "smerf" AS "smerf",
    "front_pressure_psi" AS "front_pressure_psi",
    "rear_pressure_psi" AS "rear_pressure_psi",
    "coast_A_N" AS "coast_A_N",
    "coast_B_N_per_kph" AS "coast_B_N_per_kph",
    "coast_C_N_per_kph2" AS "coast_C_N_per_kph2",
    "trans_A_coef_N" AS "trans_A_coef_N",
    "trans_B_coef_Npkph" AS "trans_B_coef_Npkph",
    "trans_C_coef_Npkph2" AS "trans_C_coef_Npkph2",
    "brake_A_coef_N" AS "brake_A_coef_N",
    "brake_B_coef_Npkph" AS "brake_B_coef_Npkph",
    "brake_C_coef_Npkph2" AS "brake_C_coef_Npkph2",
    "aero_C_coef_Npkph2" AS "aero_C_coef_Npkph2",
    "rr_alpha_N" AS "rr_alpha_N",
    "rr_beta_Npkph" AS "rr_beta_Npkph",
    "rr_a_Npkph2" AS "rr_a_Npkph2",
    "rr_b_N" AS "rr_b_N",
    "rr_c_Npkph" AS "rr_c_Npkph",
    "rr_load_kpa" AS "rr_load_kpa",
    "cycle_name" AS "cycle_name",
    "cycle_source" AS "cycle_source",
    "vde_urb_mj" AS "vde_urb_mj",
    "vde_hw_mj" AS "vde_hw_mj",
    "vde_net_mj_per_km" AS "vde_net_mj_per_km",
    "vde_total_mj_per_km" AS "vde_total_mj_per_km",
    "vde_low_mj_per_km" AS "vde_low_mj_per_km",
    "vde_mid_mj_per_km" AS "vde_mid_mj_per_km",
    "vde_high_mj_per_km" AS "vde_high_mj_per_km",
    "vde_extra_high_mj_per_km" AS "vde_extra_high_mj_per_km",
    "drive_type" AS "drive_type",
    "mro_kg" AS "mro_kg",
    "options_kg" AS "options_kg",
    "wltp_category" AS "wltp_category",
    "vde_urb_mj_per_km" AS "vde_urb_mj_per_km",
    "vde_hw_mj_per_km" AS "vde_hw_mj_per_km",
    "parasitic_A_coef_N" AS "parasitic_A_coef_N",
    "parasitic_B_coef_Npkph" AS "parasitic_B_coef_Npkph",
    "parasitic_C_coef_Npkph2" AS "parasitic_C_coef_Npkph2",
    "rrc_N_per_kN" AS "rrc_N_per_kN",
    "vde_id_parent" AS "vde_id_parent",
    "baseline_A_N" AS "baseline_A_N",
    "baseline_B_N_per_kph" AS "baseline_B_N_per_kph",
    "baseline_C_N_per_kph2" AS "baseline_C_N_per_kph2",
    "baseline_mass_kg" AS "baseline_mass_kg",
    "delta_rr_N" AS "delta_rr_N",
    "delta_brake_N" AS "delta_brake_N",
    "delta_parasitics_N" AS "delta_parasitics_N",
    "delta_aero_Npkph2" AS "delta_aero_Npkph2",
    "crr1_frac_at_120kph" AS "crr1_frac_at_120kph",
    "delta_mass_kg" AS "delta_mass_kg",
    "front_tire_id" AS "front_tire_id",
    "rear_tire_id" AS "rear_tire_id",
    "tire_improvement_pct" AS "tire_improvement_pct",
    "tire_load_mass_basis" AS "tire_load_mass_basis",
    "tire_load_mass_used_kg" AS "tire_load_mass_used_kg",
    "tire_A_final" AS "tire_A_final",
    "tire_B_final" AS "tire_B_final",
    "tire_C_final" AS "tire_C_final",
    "tire_calc_source" AS "tire_calc_source",
    "tire_calc_notes" AS "tire_calc_notes",
    "test_mass_kg" AS "test_mass_kg",
    "test_mass_low_kg" AS "test_mass_low_kg",
    "test_mass_high_kg" AS "test_mass_high_kg",
    "test_mass_basis" AS "test_mass_basis",
    "gvwr_kg" AS "gvwr_kg",
    "gcwr_kg" AS "gcwr_kg",
    "trailer_mass_kg" AS "trailer_mass_kg",
    "trailer_code" AS "trailer_code",
    "trailer_roadload_source" AS "trailer_roadload_source",
    "trailer_A_coef_N" AS "trailer_A_coef_N",
    "trailer_B_coef_Npkph" AS "trailer_B_coef_Npkph",
    "trailer_C_coef_Npkph2" AS "trailer_C_coef_Npkph2",
    "mass_rule_status" AS "mass_rule_status",
    "mass_rule_notes" AS "mass_rule_notes",
    "record_origin" AS "record_origin",
    "record_status" AS "record_status",
    "source_name" AS "source_name",
    "source_record_id" AS "source_record_id",
    "review_status" AS "review_status"
FROM "vde";

CREATE VIEW "fuelcons_db" AS
SELECT
    "id" AS "id",
    "created_at" AS "created_at",
    "vde_id" AS "vde_id",
    "electrification" AS "electrification",
    "fuel_type" AS "fuel_type",
    "eta_pt_est" AS "eta_pt_est",
    "bev_eff_drive" AS "bev_eff_drive",
    "utility_factor_pct" AS "utility_factor_pct",
    "engine_max_power_kw" AS "engine_max_power_kw",
    "engine_rpm_max_power" AS "engine_rpm_max_power",
    "engine_max_torque_nm" AS "engine_max_torque_nm",
    "engine_rpm_max_torque" AS "engine_rpm_max_torque",
    "gear_count" AS "gear_count",
    "final_drive_ratio" AS "final_drive_ratio",
    "battery_capacity_kwh" AS "battery_capacity_kwh",
    "battery_usable_kwh" AS "battery_usable_kwh",
    "bms_discharge_limit_kw" AS "bms_discharge_limit_kw",
    "bms_regen_limit_kw" AS "bms_regen_limit_kw",
    "bms_note" AS "bms_note",
    "ambient_temp_c" AS "ambient_temp_c",
    "ac_on" AS "ac_on",
    "tire_front_psi" AS "tire_front_psi",
    "tire_rear_psi" AS "tire_rear_psi",
    "scenario_payload_kg" AS "scenario_payload_kg",
    "method_note" AS "method_note",
    "energy_Wh_per_km" AS "energy_Wh_per_km",
    "fuel_km_per_l" AS "fuel_km_per_l",
    "fuel_l_per_100km" AS "fuel_l_per_100km",
    "gco2_per_km" AS "gco2_per_km",
    "energy_low_Wh_per_km" AS "energy_low_Wh_per_km",
    "energy_mid_Wh_per_km" AS "energy_mid_Wh_per_km",
    "energy_high_Wh_per_km" AS "energy_high_Wh_per_km",
    "energy_xhigh_Wh_per_km" AS "energy_xhigh_Wh_per_km",
    "fuel_low_l_per_100km" AS "fuel_low_l_per_100km",
    "fuel_mid_l_per_100km" AS "fuel_mid_l_per_100km",
    "fuel_high_l_per_100km" AS "fuel_high_l_per_100km",
    "fuel_xhigh_l_per_100km" AS "fuel_xhigh_l_per_100km",
    "gco2_low_per_km" AS "gco2_low_per_km",
    "gco2_mid_per_km" AS "gco2_mid_per_km",
    "gco2_high_per_km" AS "gco2_high_per_km",
    "gco2_xhigh_per_km" AS "gco2_xhigh_per_km",
    "energy_ftp75_Wh_per_km" AS "energy_ftp75_Wh_per_km",
    "energy_hwfet_Wh_per_km" AS "energy_hwfet_Wh_per_km",
    "energy_us06_Wh_per_km" AS "energy_us06_Wh_per_km",
    "energy_sc03_Wh_per_km" AS "energy_sc03_Wh_per_km",
    "energy_coldftp_Wh_per_km" AS "energy_coldftp_Wh_per_km",
    "fuel_ftp75_l_per_100km" AS "fuel_ftp75_l_per_100km",
    "fuel_hwfet_l_per_100km" AS "fuel_hwfet_l_per_100km",
    "fuel_us06_l_per_100km" AS "fuel_us06_l_per_100km",
    "fuel_sc03_l_per_100km" AS "fuel_sc03_l_per_100km",
    "fuel_coldftp_l_per_100km" AS "fuel_coldftp_l_per_100km",
    "gco2_ftp75_per_km" AS "gco2_ftp75_per_km",
    "gco2_hwfet_per_km" AS "gco2_hwfet_per_km",
    "gco2_us06_per_km" AS "gco2_us06_per_km",
    "gco2_sc03_per_km" AS "gco2_sc03_per_km",
    "gco2_coldftp_per_km" AS "gco2_coldftp_per_km",
    "label_program" AS "label_program",
    "label_version_year" AS "label_version_year",
    "label_vehicle_category" AS "label_vehicle_category",
    "label_cycle_set" AS "label_cycle_set",
    "label_class" AS "label_class",
    "label_offcycle_method" AS "label_offcycle_method",
    "label_offcycle_energy_factor" AS "label_offcycle_energy_factor",
    "label_offcycle_fuel_factor" AS "label_offcycle_fuel_factor",
    "label_fuel_l_per_100km" AS "label_fuel_l_per_100km",
    "label_gco2_per_km" AS "label_gco2_per_km",
    "label_range_km" AS "label_range_km",
    "energy_basis" AS "energy_basis",
    "engine_method" AS "engine_method",
    "engine_version" AS "engine_version",
    "source_vde_revision" AS "source_vde_revision",
    "assumptions_json" AS "assumptions_json",
    "provenance_json" AS "provenance_json",
    "updated_at" AS "updated_at",
    "record_origin" AS "record_origin",
    "record_status" AS "record_status",
    "source_name" AS "source_name",
    "source_record_id" AS "source_record_id",
    "review_status" AS "review_status"
FROM "fuelcons";

-- Lineage is opt-in; normal FuelCons dashboards do not traverse RUN.
CREATE VIEW "fuelcons_lineage_v1" AS
SELECT f.*,
       COALESCE((
           SELECT json_group_array(a.run_id)
           FROM (
               SELECT run_id
               FROM fuelcons_run_adoption
               WHERE fuelcons_id = f.id
               ORDER BY ordinal, run_id
           ) AS a
       ), '[]') AS adopted_run_ids_json
FROM fuelcons AS f;
