-- EcoDrive canonical physical schema v1 — Sprint 12D design only.
-- Execute in a new/disposable database. This file is not a runtime migration.
PRAGMA foreign_keys = ON;
PRAGMA user_version = 1204;

-- Primary domain entity: PROGRAM
CREATE TABLE "program" (
    "commercial_make" TEXT NOT NULL,
    "commercial_model" TEXT NOT NULL,
    "created_at" TEXT DEFAULT CURRENT_TIMESTAMP,
    "generation_name" TEXT,
    "identity_confidence" TEXT CHECK ("identity_confidence" IS NULL OR ("identity_confidence" IN ('LOW', 'MEDIUM', 'HIGH'))),
    "identity_status" TEXT NOT NULL CHECK ("identity_status" IN ('CONFIRMED', 'PROVISIONAL_SOURCE_SCOPED', 'UNRESOLVED')),
    "model_year_from" INTEGER,
    "model_year_to" INTEGER,
    "program_id" TEXT NOT NULL PRIMARY KEY CHECK (length(trim("program_id")) > 0),
    "source_identity_json" TEXT NOT NULL CHECK (json_valid("source_identity_json")),
    "source_scope" TEXT NOT NULL CHECK (length(trim("source_scope")) > 0),
    "updated_at" TEXT,
    "source_name" TEXT,
    "source_file_version" TEXT,
    "source_record_id" TEXT,
    "normalization_version" TEXT NOT NULL DEFAULT 'program_norm_v1' CHECK (length(trim("normalization_version")) > 0),
    "superseded_by_program_id" TEXT REFERENCES "program"("program_id") ON UPDATE CASCADE ON DELETE RESTRICT,
    "record_status" TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (length(trim("record_status")) > 0),
    "review_status" TEXT NOT NULL DEFAULT 'CURRENT' CHECK (length(trim("review_status")) > 0),
    CONSTRAINT "ck_program_year_range" CHECK ("model_year_from" IS NULL OR "model_year_to" IS NULL OR "model_year_from" <= "model_year_to"),
    CONSTRAINT "ck_program_not_self_superseded" CHECK ("superseded_by_program_id" IS NULL OR "superseded_by_program_id" <> "program_id")
);

-- Primary domain entity: VEHICLE_CONFIGURATION
CREATE TABLE "vehicle_configuration" (
    "architecture_properties_json" TEXT CHECK ("architecture_properties_json" IS NULL OR (json_valid("architecture_properties_json"))),
    "drive_system" TEXT,
    "engine_aspiration" TEXT,
    "engine_displacement_l" REAL,
    "engine_rated_power_kw" REAL,
    "engine_cylinders_rotors" INTEGER,
    "engine_model" TEXT,
    "engine_type" TEXT,
    "final_drive_ratio" REAL,
    "gear_count" INTEGER,
    "identity_confidence" TEXT CHECK ("identity_confidence" IS NULL OR ("identity_confidence" IN ('LOW', 'MEDIUM', 'HIGH'))),
    "identity_status" TEXT NOT NULL CHECK ("identity_status" IN ('CONFIRMED', 'SOURCE_SCOPED', 'PROVISIONAL', 'UNRESOLVED')),
    "nv_ratio" REAL,
    "program_id" TEXT NOT NULL REFERENCES "program"("program_id") ON UPDATE CASCADE ON DELETE RESTRICT,
    "propulsion_architecture" TEXT,
    "source_identity_json" TEXT NOT NULL CHECK (json_valid("source_identity_json")),
    "source_scope" TEXT NOT NULL CHECK (length(trim("source_scope")) > 0),
    "transmission_model" TEXT,
    "transmission_type" TEXT,
    "vehicle_configuration_id" TEXT NOT NULL PRIMARY KEY CHECK (length(trim("vehicle_configuration_id")) > 0),
    "source_name" TEXT,
    "source_file_version" TEXT,
    "source_record_id" TEXT,
    "normalization_version" TEXT NOT NULL DEFAULT 'configuration_norm_v1' CHECK (length(trim("normalization_version")) > 0),
    "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TEXT,
    "record_status" TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (length(trim("record_status")) > 0),
    "review_status" TEXT NOT NULL DEFAULT 'CURRENT' CHECK (length(trim("review_status")) > 0)
);

-- Primary domain entity: COMPONENT_DB
CREATE TABLE "component_db" (
    "capacity_kwh" REAL,
    "component_domain" TEXT NOT NULL CHECK ("component_domain" IN ('ENGINE', 'TRANSMISSION', 'EMOTOR', 'BATTERY', 'BRAKE', 'AXLE_HUBS', 'PARASITIC', 'OTHER')),
    "component_id" TEXT NOT NULL PRIMARY KEY CHECK (length(trim("component_id")) > 0),
    "custom_properties_json" TEXT CHECK ("custom_properties_json" IS NULL OR (json_valid("custom_properties_json"))),
    "data_artifact_ref" TEXT,
    "hardware_reference" TEXT,
    "manufacturer" TEXT,
    "mass_kg" REAL,
    "model" TEXT,
    "model_artifact_ref" TEXT,
    "nominal_voltage_v" REAL,
    "provenance_json" TEXT NOT NULL CHECK (json_valid("provenance_json")),
    "rated_power_kw" REAL,
    "rated_torque_nm" REAL,
    "ratio" REAL,
    "source_name" TEXT,
    "source_record_id" TEXT,
    "source_file_version" TEXT,
    "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TEXT,
    "record_status" TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (length(trim("record_status")) > 0),
    "review_status" TEXT NOT NULL DEFAULT 'CURRENT' CHECK (length(trim("review_status")) > 0)
);

-- Primary domain entity: TIRE_DB
CREATE TABLE "tire_db" (
    "break_in_distance_km" REAL,
    "calculation_mode" TEXT,
    "conditioning_notes" TEXT,
    "created_at" TEXT DEFAULT CURRENT_TIMESTAMP,
    "effective_circumference_override_mm" REAL,
    "force_unit" TEXT,
    "is_active" INTEGER DEFAULT 1 CHECK ("is_active" IS NULL OR ("is_active" IN (0, 1))),
    "is_broken_in" INTEGER DEFAULT 0 CHECK ("is_broken_in" IS NULL OR ("is_broken_in" IN (0, 1))),
    "is_estimated_value" INTEGER DEFAULT 0 CHECK ("is_estimated_value" IS NULL OR ("is_estimated_value" IN (0, 1))),
    "is_tested_value" INTEGER DEFAULT 0 CHECK ("is_tested_value" IS NULL OR ("is_tested_value" IN (0, 1))),
    "iso_condition_notes" TEXT,
    "iso_corrected_rrc_n_per_kn" REAL,
    "iso_rolling_resistance_force_n" REAL,
    "iso_rrc_n_per_kn" REAL,
    "iso_test_load_n" REAL,
    "iso_test_pressure_kpa" REAL,
    "iso_test_speed_kph" REAL,
    "load_index" TEXT,
    "load_unit" TEXT,
    "manufacturer" TEXT NOT NULL,
    "model" TEXT NOT NULL,
    "notes" TEXT,
    "pressure_unit" TEXT,
    "record_origin" TEXT NOT NULL DEFAULT 'LEGACY' CHECK (length(trim("record_origin")) > 0),
    "reference_temperature_c" REAL,
    "rr_method" TEXT,
    "rr_n_per_kn" REAL NOT NULL CHECK ("rr_n_per_kn" >= 0),
    "rr_quality" TEXT,
    "rr_source" TEXT,
    "rr_value_source_note" TEXT,
    "sae_a" REAL,
    "sae_alpha" REAL,
    "sae_b" REAL,
    "sae_beta" REAL,
    "sae_c" REAL,
    "sae_force_unit" TEXT,
    "sae_load_unit" TEXT,
    "sae_pressure_unit" TEXT,
    "sae_reference_load_n" REAL,
    "sae_reference_pressure_kpa" REAL,
    "sae_speed_unit" TEXT,
    "size_code" TEXT,
    "smerf" REAL,
    "source_name" TEXT,
    "source_record_id" TEXT,
    "speed_rating" TEXT,
    "speed_unit" TEXT,
    "standard_family" TEXT NOT NULL,
    "standard_version" TEXT,
    "temperature_correction_applied" INTEGER DEFAULT 0 CHECK ("temperature_correction_applied" IS NULL OR ("temperature_correction_applied" IN (0, 1))),
    "test_date" TEXT,
    "test_load_value" REAL,
    "test_method" TEXT,
    "test_mileage_km" REAL,
    "test_pressure_value" REAL,
    "test_source" TEXT,
    "test_speed_value" REAL,
    "test_temperature_c" REAL,
    "tire_id" INTEGER NOT NULL PRIMARY KEY,
    "tire_test_code" TEXT NOT NULL UNIQUE,
    "updated_at" TEXT,
    "source_file_version" TEXT,
    "provenance_json" TEXT CHECK ("provenance_json" IS NULL OR (json_valid("provenance_json"))),
    "record_status" TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (length(trim("record_status")) > 0),
    "review_status" TEXT NOT NULL DEFAULT 'CURRENT' CHECK (length(trim("review_status")) > 0)
);

-- Primary domain entity: COMPONENT_INSTANCE
CREATE TABLE "component_instance" (
    "component_domain" TEXT NOT NULL CHECK ("component_domain" IN ('ENGINE', 'TRANSMISSION', 'EMOTOR', 'BATTERY', 'BRAKE', 'AXLE_HUBS', 'PARASITIC', 'TIRE', 'OTHER')),
    "component_id" TEXT REFERENCES "component_db"("component_id") ON UPDATE CASCADE ON DELETE RESTRICT,
    "component_instance_id" TEXT NOT NULL PRIMARY KEY CHECK (length(trim("component_instance_id")) > 0),
    "instance_properties_json" TEXT CHECK ("instance_properties_json" IS NULL OR (json_valid("instance_properties_json"))),
    "position" TEXT,
    "provenance_json" TEXT NOT NULL CHECK (json_valid("provenance_json")),
    "quantity" INTEGER NOT NULL DEFAULT 1 CHECK ("quantity" > 0),
    "role" TEXT,
    "tire_id" INTEGER REFERENCES "tire_db"("tire_id") ON UPDATE CASCADE ON DELETE RESTRICT,
    "vehicle_configuration_id" TEXT NOT NULL REFERENCES "vehicle_configuration"("vehicle_configuration_id") ON UPDATE CASCADE ON DELETE CASCADE,
    "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TEXT,
    "record_status" TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (length(trim("record_status")) > 0),
    "review_status" TEXT NOT NULL DEFAULT 'CURRENT' CHECK (length(trim("review_status")) > 0),
    CONSTRAINT "ck_component_instance_single_target" CHECK (NOT ("component_id" IS NOT NULL AND "tire_id" IS NOT NULL)),
    CONSTRAINT "ck_component_instance_typed_target" CHECK (("component_domain" = 'TIRE' AND "component_id" IS NULL) OR ("component_domain" <> 'TIRE' AND "tire_id" IS NULL))
);

-- Primary domain entity: COMPONENT_RESOLUTION
CREATE TABLE "component_resolution" (
    "boundary" TEXT NOT NULL,
    "component_resolution_id" TEXT NOT NULL PRIMARY KEY CHECK (length(trim("component_resolution_id")) > 0),
    "conditions_json" TEXT CHECK ("conditions_json" IS NULL OR (json_valid("conditions_json"))),
    "confidence" TEXT CHECK ("confidence" IS NULL OR ("confidence" IN ('LOW', 'MEDIUM', 'HIGH'))),
    "fidelity_level" TEXT CHECK ("fidelity_level" IS NULL OR ("fidelity_level" IN ('L0', 'L1', 'L2', 'L3'))),
    "input_component_instance_ids_json" TEXT CHECK ("input_component_instance_ids_json" IS NULL OR (json_valid("input_component_instance_ids_json"))),
    "method" TEXT NOT NULL,
    "provenance_json" TEXT NOT NULL CHECK (json_valid("provenance_json")),
    "resolved_A_N" REAL,
    "resolved_B_N_per_kph" REAL,
    "resolved_C_N_per_kph2" REAL,
    "source_run_ids_json" TEXT CHECK ("source_run_ids_json" IS NULL OR (json_valid("source_run_ids_json"))),
    "vehicle_configuration_id" TEXT REFERENCES "vehicle_configuration"("vehicle_configuration_id") ON UPDATE CASCADE ON DELETE SET NULL,
    "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TEXT,
    "record_status" TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (length(trim("record_status")) > 0),
    "review_status" TEXT NOT NULL DEFAULT 'CURRENT' CHECK (length(trim("review_status")) > 0)
);

-- Primary domain entity: VDE
CREATE TABLE "vde" (
    "aero_C_coef_Npkph2" REAL,
    "baseline_A_N" REAL,
    "baseline_B_N_per_kph" REAL,
    "baseline_C_N_per_kph2" REAL,
    "baseline_mass_kg" REAL,
    "brake_A_coef_N" REAL,
    "brake_B_coef_Npkph" REAL,
    "brake_C_coef_Npkph2" REAL,
    "category" TEXT NOT NULL,
    "cda_m2" REAL,
    "coast_A_N" REAL,
    "coast_B_N_per_kph" REAL,
    "coast_C_N_per_kph2" REAL,
    "created_at" TEXT DEFAULT CURRENT_TIMESTAMP,
    "crr1_frac_at_120kph" REAL,
    "cycle_name" TEXT,
    "cycle_source" TEXT,
    "roadload_temperature_c" REAL,
    "roadload_ambient_pressure_kpa" REAL,
    "delta_aero_Npkph2" REAL,
    "delta_brake_N" REAL,
    "delta_mass_kg" REAL,
    "delta_parasitics_N" REAL,
    "delta_rr_N" REAL,
    "drive_type" TEXT,
    "engine_aspiration" TEXT,
    "engine_model" TEXT,
    "engine_size_l" REAL,
    "engine_type" TEXT,
    "front_pressure_psi" REAL,
    "front_tire_id" INTEGER REFERENCES "tire_db"("tire_id") ON UPDATE CASCADE ON DELETE RESTRICT,
    "gcwr_kg" REAL,
    "gvwr_kg" REAL,
    "id" INTEGER NOT NULL PRIMARY KEY,
    "inertia_class" REAL,
    "legislation" TEXT NOT NULL CHECK ("legislation" IN ('EPA', 'WLTP', 'BRA', 'OTHER')),
    "make" TEXT NOT NULL,
    "mass_kg" REAL NOT NULL CHECK ("mass_kg" >= 0),
    "mass_rule_notes" TEXT,
    "mass_rule_status" TEXT,
    "model" TEXT NOT NULL,
    "mro_kg" REAL,
    "notes" TEXT,
    "options_kg" REAL,
    "parasitic_A_coef_N" REAL,
    "parasitic_B_coef_Npkph" REAL,
    "parasitic_C_coef_Npkph2" REAL,
    "payload_kg" REAL,
    "rear_pressure_psi" REAL,
    "rear_tire_id" INTEGER REFERENCES "tire_db"("tire_id") ON UPDATE CASCADE ON DELETE RESTRICT,
    "record_origin" TEXT NOT NULL DEFAULT 'LEGACY' CHECK (length(trim("record_origin")) > 0),
    "record_status" TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (length(trim("record_status")) > 0),
    "review_status" TEXT NOT NULL DEFAULT 'CURRENT' CHECK (length(trim("review_status")) > 0),
    "rr_a_Npkph2" REAL,
    "rr_alpha_N" REAL,
    "rr_b_N" REAL,
    "rr_beta_Npkph" REAL,
    "rr_c_Npkph" REAL,
    "rr_load_kpa" REAL,
    "rrc_N_per_kN" REAL,
    "smerf" REAL,
    "source_name" TEXT,
    "source_payload_json" TEXT CHECK ("source_payload_json" IS NULL OR (json_valid("source_payload_json"))),
    "source_record_id" TEXT,
    "source_semantic_status" TEXT NOT NULL CHECK ("source_semantic_status" IN ('DIRECT', 'PARTIAL', 'UNRESOLVED')),
    "test_mass_basis" TEXT,
    "test_mass_high_kg" REAL,
    "test_mass_kg" REAL,
    "test_mass_low_kg" REAL,
    "tire_A_final" REAL,
    "tire_B_final" REAL,
    "tire_C_final" REAL,
    "tire_calc_notes" TEXT,
    "tire_calc_source" TEXT,
    "tire_improvement_pct" REAL,
    "tire_load_mass_basis" TEXT,
    "tire_load_mass_used_kg" REAL,
    "tire_rr_note" TEXT,
    "tire_size" TEXT,
    "trailer_A_coef_N" REAL,
    "trailer_B_coef_Npkph" REAL,
    "trailer_C_coef_Npkph2" REAL,
    "trailer_code" TEXT,
    "trailer_mass_kg" REAL,
    "trailer_roadload_source" TEXT,
    "trans_A_coef_N" REAL,
    "trans_B_coef_Npkph" REAL,
    "trans_C_coef_Npkph2" REAL,
    "transmission_model" TEXT,
    "transmission_type" TEXT,
    "updated_at" TEXT,
    "vde_extra_high_mj_per_km" REAL,
    "vde_high_mj_per_km" REAL,
    "vde_hw_mj" REAL,
    "vde_hw_mj_per_km" REAL,
    "vde_id_parent" INTEGER REFERENCES "vde"("id") ON UPDATE CASCADE ON DELETE RESTRICT,
    "vde_low_mj_per_km" REAL,
    "vde_mid_mj_per_km" REAL,
    "vde_net_mj_per_km" REAL,
    "vde_total_mj_per_km" REAL,
    "vde_urb_mj" REAL,
    "vde_urb_mj_per_km" REAL,
    "vehicle_configuration_id" TEXT NOT NULL REFERENCES "vehicle_configuration"("vehicle_configuration_id") ON UPDATE CASCADE ON DELETE RESTRICT,
    "weight_dist_fr_pct" REAL,
    "wltp_category" INTEGER,
    "year" INTEGER,
    "source_file_version" TEXT,
    "normalization_version" TEXT CHECK ("normalization_version" IS NULL OR (length(trim("normalization_version")) > 0)),
    "provenance_json" TEXT CHECK ("provenance_json" IS NULL OR (json_valid("provenance_json")))
);

-- Primary domain entity: RUN
CREATE TABLE "run" (
    "assumptions_json" TEXT CHECK ("assumptions_json" IS NULL OR (json_valid("assumptions_json"))),
    "conditions_json" TEXT CHECK ("conditions_json" IS NULL OR (json_valid("conditions_json"))),
    "confidence" TEXT CHECK ("confidence" IS NULL OR ("confidence" IN ('LOW', 'MEDIUM', 'HIGH'))),
    "created_at" TEXT DEFAULT CURRENT_TIMESTAMP,
    "evidence_kind" TEXT NOT NULL CHECK ("evidence_kind" IN ('ENGINEERING', 'HOMOLOGATION', 'MONITORING', 'BENCHMARK', 'SOURCE_RECORD')),
    "fidelity_level" TEXT CHECK ("fidelity_level" IS NULL OR ("fidelity_level" IN ('L0', 'L1', 'L2', 'L3'))),
    "method" TEXT,
    "method_version" TEXT,
    "procedure_code" TEXT,
    "procedure_description" TEXT,
    "provenance_json" TEXT NOT NULL CHECK (json_valid("provenance_json")),
    "result_details_json" TEXT CHECK ("result_details_json" IS NULL OR (json_valid("result_details_json"))),
    "run_id" TEXT NOT NULL PRIMARY KEY CHECK (length(trim("run_id")) > 0),
    "run_type" TEXT NOT NULL CHECK ("run_type" IN ('TEST', 'SIMULATION', 'ESTIMATION', 'CALCULATION', 'ML_PREDICTION', 'DECLARED_RESULT')),
    "source_name" TEXT,
    "source_record_id" TEXT,
    "vde_id" INTEGER NOT NULL REFERENCES "vde"("id") ON UPDATE CASCADE ON DELETE CASCADE,
    "source_file_version" TEXT,
    "updated_at" TEXT,
    "record_status" TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (length(trim("record_status")) > 0),
    "review_status" TEXT NOT NULL DEFAULT 'CURRENT' CHECK (length(trim("review_status")) > 0),
    CONSTRAINT "uq_run_id_vde" UNIQUE ("run_id", "vde_id")
);

-- Primary domain entity: FUELCONS
CREATE TABLE "fuelcons" (
    "ac_on" INTEGER CHECK ("ac_on" IS NULL OR ("ac_on" IN (0, 1))),
    "ambient_temp_c" REAL,
    "assumptions_json" TEXT,
    "battery_capacity_kwh" REAL,
    "battery_usable_kwh" REAL,
    "bev_eff_drive" REAL,
    "bms_discharge_limit_kw" REAL,
    "bms_note" TEXT,
    "bms_regen_limit_kw" REAL,
    "comparison_basis" TEXT NOT NULL DEFAULT 'LEGACY_UNSPECIFIED' CHECK (length(trim("comparison_basis")) > 0),
    "created_at" TEXT DEFAULT CURRENT_TIMESTAMP,
    "electrification" TEXT NOT NULL CHECK ("electrification" IN ('NONE', 'ICE', 'MHEV', 'HEV', 'PHEV', 'BEV', 'FCEV', 'OTHER')),
    "energy_Wh_per_km" REAL,
    "energy_basis" TEXT CHECK ("energy_basis" IS NULL OR ("energy_basis" IN ('VDE_TOTAL', 'VDE_NET', 'SOURCE_DECLARED', 'OTHER'))),
    "energy_coldftp_Wh_per_km" REAL,
    "energy_ftp75_Wh_per_km" REAL,
    "energy_high_Wh_per_km" REAL,
    "energy_hwfet_Wh_per_km" REAL,
    "energy_low_Wh_per_km" REAL,
    "energy_mid_Wh_per_km" REAL,
    "energy_sc03_Wh_per_km" REAL,
    "energy_us06_Wh_per_km" REAL,
    "energy_xhigh_Wh_per_km" REAL,
    "engine_max_power_kw" REAL,
    "engine_max_torque_nm" REAL,
    "engine_method" TEXT,
    "engine_rpm_max_power" INTEGER,
    "engine_rpm_max_torque" INTEGER,
    "engine_version" TEXT,
    "eta_pt_est" REAL,
    "final_drive_ratio" REAL,
    "fuel_coldftp_l_per_100km" REAL,
    "fuel_ftp75_l_per_100km" REAL,
    "fuel_high_l_per_100km" REAL,
    "fuel_hwfet_l_per_100km" REAL,
    "fuel_km_per_l" REAL,
    "fuel_l_per_100km" REAL,
    "fuel_low_l_per_100km" REAL,
    "fuel_mid_l_per_100km" REAL,
    "fuel_sc03_l_per_100km" REAL,
    "fuel_type" TEXT,
    "fuel_us06_l_per_100km" REAL,
    "fuel_xhigh_l_per_100km" REAL,
    "gco2_coldftp_per_km" REAL,
    "gco2_ftp75_per_km" REAL,
    "gco2_high_per_km" REAL,
    "gco2_hwfet_per_km" REAL,
    "gco2_low_per_km" REAL,
    "gco2_mid_per_km" REAL,
    "gco2_per_km" REAL,
    "gco2_sc03_per_km" REAL,
    "gco2_us06_per_km" REAL,
    "gco2_xhigh_per_km" REAL,
    "gear_count" INTEGER,
    "id" INTEGER NOT NULL PRIMARY KEY,
    "label_class" TEXT,
    "label_cycle_set" TEXT,
    "label_fuel_l_per_100km" REAL,
    "label_gco2_per_km" REAL,
    "label_offcycle_energy_factor" REAL,
    "label_offcycle_fuel_factor" REAL,
    "label_offcycle_method" TEXT,
    "label_program" TEXT,
    "label_range_km" REAL,
    "label_vehicle_category" TEXT,
    "label_version_year" INTEGER,
    "method_note" TEXT,
    "provenance_json" TEXT,
    "record_origin" TEXT NOT NULL DEFAULT 'LEGACY' CHECK (length(trim("record_origin")) > 0),
    "record_status" TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (length(trim("record_status")) > 0),
    "review_status" TEXT NOT NULL DEFAULT 'CURRENT' CHECK (length(trim("review_status")) > 0),
    "scenario_payload_kg" REAL,
    "source_name" TEXT,
    "source_record_id" TEXT,
    "source_vde_revision" TEXT,
    "tire_front_psi" REAL,
    "tire_rear_psi" REAL,
    "updated_at" TEXT,
    "utility_factor_pct" REAL CHECK ("utility_factor_pct" IS NULL OR ("utility_factor_pct" BETWEEN 0 AND 100)),
    "vde_id" INTEGER NOT NULL REFERENCES "vde"("id") ON UPDATE CASCADE ON DELETE CASCADE,
    "source_file_version" TEXT,
    "normalization_version" TEXT CHECK ("normalization_version" IS NULL OR (length(trim("normalization_version")) > 0)),
    "reference_fuelcons_id" INTEGER REFERENCES "fuelcons"("id") ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT "uq_fuelcons_id_vde" UNIQUE ("id", "vde_id")
);

-- Physical lineage helper; not a tenth primary domain entity.
CREATE TABLE "fuelcons_run_adoption" (
    "fuelcons_id" INTEGER NOT NULL,
    "run_id" TEXT NOT NULL,
    "vde_id" INTEGER NOT NULL REFERENCES "vde"("id") ON UPDATE CASCADE ON DELETE CASCADE,
    "adoption_role" TEXT NOT NULL CHECK ("adoption_role" IN ('PRIMARY', 'SUPPORTING', 'POST_PROCESSING_INPUT')),
    "result_dimension" TEXT NOT NULL DEFAULT 'ALL',
    "ordinal" INTEGER NOT NULL DEFAULT 0 CHECK ("ordinal" >= 0),
    "details_json" TEXT CHECK ("details_json" IS NULL OR json_valid("details_json")),
    "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("fuelcons_id", "run_id", "result_dimension"),
    FOREIGN KEY ("fuelcons_id", "vde_id") REFERENCES "fuelcons"("id", "vde_id") ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY ("run_id", "vde_id") REFERENCES "run"("run_id", "vde_id") ON UPDATE CASCADE ON DELETE CASCADE
);

-- Physical adoption helper; Component Resolution remains optional.
CREATE TABLE "vde_component_resolution" (
    "vde_id" INTEGER NOT NULL REFERENCES "vde"("id") ON UPDATE CASCADE ON DELETE CASCADE,
    "component_resolution_id" TEXT NOT NULL REFERENCES "component_resolution"("component_resolution_id") ON UPDATE CASCADE ON DELETE CASCADE,
    "boundary" TEXT NOT NULL,
    "adoption_role" TEXT NOT NULL DEFAULT 'ADOPTED' CHECK ("adoption_role" IN ('ADOPTED', 'SUPPORTING', 'SUPERSEDED')),
    "ordinal" INTEGER NOT NULL DEFAULT 0 CHECK ("ordinal" >= 0),
    "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("vde_id", "component_resolution_id", "boundary")
);

-- Indexes are justified by the audited application/source query paths.
CREATE INDEX "idx_program_make_model_status" ON "program" ("commercial_make", "commercial_model", "identity_status");
CREATE INDEX "idx_program_source_identity" ON "program" ("source_scope", "source_name", "source_record_id", "source_file_version");
CREATE INDEX "idx_program_superseded" ON "program" ("superseded_by_program_id");
CREATE INDEX "idx_vc_program" ON "vehicle_configuration" ("program_id");
CREATE INDEX "idx_vc_source_identity" ON "vehicle_configuration" ("source_scope", "source_name", "source_record_id", "source_file_version");
CREATE INDEX "idx_vc_architecture" ON "vehicle_configuration" ("engine_type", "transmission_type", "drive_system");
CREATE INDEX "idx_component_domain_make_model" ON "component_db" ("component_domain", "manufacturer", "model");
CREATE INDEX "idx_component_source" ON "component_db" ("source_name", "source_record_id", "source_file_version");
CREATE INDEX "idx_tire_active_make_model" ON "tire_db" ("is_active", "manufacturer", "model", "size_code");
CREATE INDEX "idx_component_instance_configuration" ON "component_instance" ("vehicle_configuration_id", "component_domain", "role", "position");
CREATE INDEX "idx_component_instance_component" ON "component_instance" ("component_id");
CREATE INDEX "idx_component_instance_tire" ON "component_instance" ("tire_id");
CREATE INDEX "idx_resolution_configuration" ON "component_resolution" ("vehicle_configuration_id", "boundary");
CREATE INDEX "idx_vde_configuration" ON "vde" ("vehicle_configuration_id", "id");
CREATE INDEX "idx_vde_parent" ON "vde" ("vde_id_parent");
CREATE INDEX "idx_vde_make_model_year" ON "vde" ("make", "model", "year");
CREATE INDEX "idx_vde_category_legislation" ON "vde" ("category", "legislation", "make");
CREATE INDEX "idx_vde_updated" ON "vde" ("updated_at" DESC, "created_at" DESC);
CREATE INDEX "idx_vde_source" ON "vde" ("source_name", "source_record_id", "source_file_version");
CREATE INDEX "idx_run_vde_created" ON "run" ("vde_id", "created_at" DESC);
CREATE INDEX "idx_run_source" ON "run" ("source_name", "source_record_id", "source_file_version");
CREATE INDEX "idx_run_type_kind" ON "run" ("run_type", "evidence_kind");
CREATE INDEX "idx_fuelcons_vde_created" ON "fuelcons" ("vde_id", "created_at" DESC);
CREATE INDEX "idx_fuelcons_browse" ON "fuelcons" ("electrification", "record_origin", "created_at" DESC);
CREATE INDEX "idx_fuelcons_power" ON "fuelcons" ("engine_max_power_kw");
CREATE INDEX "idx_fuelcons_source" ON "fuelcons" ("source_name", "source_record_id", "source_file_version");
CREATE INDEX "idx_adoption_run" ON "fuelcons_run_adoption" ("run_id", "fuelcons_id");
CREATE INDEX "idx_vde_resolution_resolution" ON "vde_component_resolution" ("component_resolution_id", "vde_id");
